# Site settings
title: Namrata Khatri
description: Jekyll Theme Minimal Resume
baseurl: "https://npkhatri.blogspot.com # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Namrata Khatri
user_description: I'm a data science enthusiastic, just finished a data science certificate, searching for the next challenge; no task is too scary nor too difficult. Lately working on Mix Market Modeling project. Visit my blog here":" <a href="https://namratakhatri.com" target="_blank">https://namratakhatri.com</a>
user_title: Software Engineer
email: namratakhatri@gmail.com
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytic
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
